In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import random

We will create a MineSweeper game with a board size of (a,a). The game will be implemented using two matrix of size (a,a), which will be named the Game board and the Mine board. 

The Game board will be a matrix with numbers ranging from -2 to 8, where -1 represent a bomb, -2 represent an uncover cell, and 0-8 represent a cell with the number of bombs surrounding it. It will be the game board observed by the player.

The Mine Board will be a matrix with 0 and 1, where 1 is a bomb and 0 is a safe cell. This matrix will store the mine location on the board.

In [97]:
class minesweeper_game(object):
    def __init__(self, len_board):
        self.len_board = len_board
        self.mine_board = self.create_mine_board()
        self.game_board = np.full((len_board,len_board), -2)
    
    def create_mine_board(self):
        mine_board = np.full((self.len_board,self.len_board),0)  #We define a np.array of size (a,a) with only zeroes
        mines = [] #list of mines
        while len(mines) < self.len_board: #we want a mines
            mine_coord = (random.randint(0, self.len_board-1), random.randint(0, self.len_board-1)) #we consider the coordinate of the mine
            if mine_coord not in mines: 
                mines.append(mine_coord)
                mine_board[mine_coord] = 1
        return mine_board

    def create_game_board(self, mine_board):
        game_board = np.full((self.len_board,self.len_board), 0)
        for i in range(0,self.len_board):
            for j in range(0, self.len_board):
                if mine_board[(i,j)] == 1:
                    game_board[(i,j)] = -1
        return game_board
                    
    def game_status(self):
        for i in range(0,self.len_board):
            for j in range(0, self.len_board):
                if self.game_board[(i,j)] == -1:
                    return print("You lost!") # You lost!. You uncovered a mine
        uncovered_cells = self.len_board*self.len_board
        for i in range(0,self.len_board):
            for j in range(0, self.len_board):
                if (self.game_board[(i,j)] != -1):
                    uncovered_cells += 1
        if uncovered_cells == self.len_board*self.len_board - self.len_board:
            return print("You won!") #You uncovered all of cells without a bomb (There are "a" bombs).
        else:
            return print("You are still missing bombs")
    
        
      

In [100]:
game = minesweeper_game(8)
print(game.mine_board)
print(game.game_board)
game.game_status()

[[1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]]
[[-2 -2 -2 -2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2 -2 -2 -2]]
You are still missing bombs
